name: blis
favicon: null
layout_spectrum: 0.48107690131291747
typography_spectrum: 0.849315348546952
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.08705260325223207
  lightness: 0.7702636702451855
  saturation: 0.60283044539392
  rhythmicContrast: 0.21840135683305562
purpose: []
